### ISSUE TITLE
Compile Error: User-defined type not defined

### ISSUE THREAD

**Issue by cyril23** [Elmetayer/VBA-outlook-export#1]
When executing your script within Microsoft Outlook Professional Plus 2019, it shows the following message:

![image](https://user-images.githubusercontent.com/5645872/82896453-4319f580-9f56-11ea-865f-1fa7c70bcd70.png)
(English: `Compile Error: User-defined type not defined`)

![image](https://user-images.githubusercontent.com/5645872/82896489-52993e80-9f56-11ea-8226-fd1da288fee5.png)

The problem occurs around `Function cleanupEmailAddress(text As String) As String`

I already tried adding some libraries I googled to be helpful in some cases, without success:
![image](https://user-images.githubusercontent.com/5645872/82896553-72306700-9f56-11ea-9235-b1833a5f9686.png)

**Comment by Elmetayer** [comment]
The macro is using RegExp, so you have to enable "Microsoft VBScript Regular Expressions" in the list of references.
In the VBA editor, go to the menu Tools, then References, then select "Microsoft VBScript Regular Expressions x.x" where x.x is the current version on your system (e.g. 5.5)

Tell me if this solves your issue !

**Comment by cyril23** [comment]
thanks! that solved it. great tool by the way! I needed it because Outlook doesn't export the date column in CSV.
